<?php

use yii\db\Schema;
use yii\db\Migration;

class m190228_151649_userDataInsert extends Migration
{

    public function init()
    {
        $this->db = 'db';
        parent::init();
    }

    public function safeUp()
    {
        $this->batchInsert('{{%user}}',
                           ["id", "username", "email", "nama", "password_hash", "password_reset_token", "auth_key", "avatar", "tempat_lahir", "tanggal_lahir", "alamat", "job", "instansi", "status", "created_at", "updated_at"],
                            [
    [
        'id' => '22',
        'username' => 'adryanev',
        'email' => 'adryanekavandra@gmail.com',
        'nama' => 'Adryan Eka Vandra',
        'password_hash' => '$2y$13$.K0ULLVA2FA0TWHMMO8bcuUE8OANZzYZFMgfKaIxz.BNQadbokeIe',
        'password_reset_token' => null,
        'auth_key' => '_O2o3Ymb-BLTvtgBYne-Ysh82GzybS3q',
        'avatar' => 'DSC06568.jpg',
        'tempat_lahir' => 'Tembilahan',
        'tanggal_lahir' => '1996-08-09',
        'alamat' => 'Pekanbaru',
        'job' => 'Mahasiswa',
        'instansi' => 'UIN SUSKA RIAU',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '23',
        'username' => 'radinaldn',
        'email' => 'radinal.dwiki.novendra@students.uin-suska.ac.id',
        'nama' => 'radinal',
        'password_hash' => '$2y$13$zalqCcAyp0z8kYev3JOLg.DKUSkehMlIbUP0isL2dX5sRQ0A/jDJu',
        'password_reset_token' => null,
        'auth_key' => '28NtfcB-GuzNoAkJ7FHrr45G1coXCQCx',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'Co-Founder',
        'instansi' => 'TopApp',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '24',
        'username' => 'nsh',
        'email' => 'nazruddin.safaat@gmail.com',
        'nama' => 'nsh',
        'password_hash' => '$2y$13$UcvpIJ/V0tGJLdQXJG6x6e4f56/N/ti82PD/rSinPMaY2O2O5e/um',
        'password_reset_token' => null,
        'auth_key' => 'axWYYQXBumv1cPONydmvIZ3QUBwSu4My',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'konsultant',
        'instansi' => 'uin',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '26',
        'username' => 'sabil',
        'email' => 'sabil@gmail.com',
        'nama' => 'sanbil',
        'password_hash' => '$2y$13$4GIBx.1rtc0PIWmFPemZJeJ6mXImUiaiuJVCfLgmfJlgbdknu8pue',
        'password_reset_token' => null,
        'auth_key' => 'UjVnzoSIXuHDxjSEOhNb0WuOvI4EF4_h',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'sabil',
        'instansi' => 'sabil',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '27',
        'username' => 'tyo0302',
        'email' => 'prasetyo.nugroho@students.uin-suska.ac.id',
        'nama' => 'Prasetyo Nugroho',
        'password_hash' => '$2y$13$Z9C.ulOEQvVSTYCrdrs4w.I5Ev52zGiB4sNBx/sodK7vu5dch6vU.',
        'password_reset_token' => null,
        'auth_key' => 'sF7Nabys2CDZ7Lg_W5-6eQ-Kc62xOCqv',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'Kuliah',
        'instansi' => '03021996',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '28',
        'username' => 'fulltime',
        'email' => 'fuadhelmi2@gmail.com',
        'nama' => 'fuad helmi',
        'password_hash' => '$2y$13$pCrEJMAUNLiYPpRdo48aAOK4SOPmDbzUSwNFUsaAf9shmC2TOlqWW',
        'password_reset_token' => null,
        'auth_key' => 'DSrLeyXT6wr2qLpKgXBJlGpAMDltcau9',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'sekretaris',
        'instansi' => 'spr ponbaja',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '29',
        'username' => 'Ratna Sari',
        'email' => 'ratna.sari@students.uin-suska.ac.id',
        'nama' => 'Ratna Sari',
        'password_hash' => '$2y$13$kAZqSs7OKKBzBEA0Z6qeKecelLybBrFEEvcT00xkdl1Jb/eJ0bj8C',
        'password_reset_token' => null,
        'auth_key' => 'zyFGyaVumSvA4K1NEhFdw7WdDsqlVLKt',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'Mahasiswa',
        'instansi' => 'Inkubator jurusan teknik informatika',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '30',
        'username' => 'tanjungpinang',
        'email' => 'tanjungpinang@gmail.com',
        'nama' => 'tanjungpinang',
        'password_hash' => '$2y$13$Pp45FBgn0XwOPFYaklGo9.Ae2FRxqO6UgUO5AHWRvcvbCzcl/qZ.m',
        'password_reset_token' => null,
        'auth_key' => 'fcJrunnVJMOUBJN0ColJVCFSPmQcWZMX',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'it consultant',
        'instansi' => 'tanjungpinang',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '31',
        'username' => 'ryandwijaya',
        'email' => 'ryan.jaya21@gmail.com',
        'nama' => 'ryan dwijaya',
        'password_hash' => '$2y$13$yqOgMXsUIZMCXz5jAwzUUOs9rI3pg9ZMkINex3MNx9xB/OdHUB5Jm',
        'password_reset_token' => null,
        'auth_key' => '5YnEw-V1kMFR12iXnMY7BCvvTrFNsN77',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'Mahasiswa',
        'instansi' => 'UIN SUSKA RIAU',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '32',
        'username' => 'rdwijayaa',
        'email' => 'pulak.alaadar@gmail.com',
        'nama' => 'test',
        'password_hash' => '$2y$13$i1iCcSO6ht4XwgPm9Ri2AeMRbZg.tDgMry5V967NhCK.J0xYZPwDm',
        'password_reset_token' => null,
        'auth_key' => '8vzHDq0JKIbwbva0t7NN5DJ2RCJC-_4X',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'Mahasiswa',
        'instansi' => 'UIN SUSKA RIAU',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '33',
        'username' => 'jbenastey',
        'email' => 'jbenastey@gmail.com',
        'nama' => 'Jihad',
        'password_hash' => '$2y$13$6jEhKos4a251f6wZltiVAuY/O1DLc1mvW0VB9E50cKFA1pAUVDU2.',
        'password_reset_token' => null,
        'auth_key' => 'G8WEuRneptsbo8bLRZ29MrznjnMdcc9b',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'Mahasiswa',
        'instansi' => 'UIN SUSKA RIAU',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '34',
        'username' => 'rdwijayaaa',
        'email' => 'pulak.alakadar@gmail.com',
        'nama' => 'ryan',
        'password_hash' => '$2y$13$mRrnJabVTd9qwuOXQHP1OOwCDbSk8ZbGOU50WSYDoR0Z6eYmkr.nm',
        'password_reset_token' => null,
        'auth_key' => 'fmiZqm6r8vlzdpF_omOCsXAq_aNpRYCl',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'MAHASISWA',
        'instansi' => 'UIN SUSKA RIAU',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '35',
        'username' => 'badell',
        'email' => 'badellmen@gmail.com',
        'nama' => 'badell',
        'password_hash' => '$2y$13$TQuAYUkg5yI8/3ZqKglsa.94bfLVK.GzTFgvLvMp/h9Wnw4K1d7Fm',
        'password_reset_token' => null,
        'auth_key' => 'M-TBU3dvh7XGPOewK1yXQIHlVlDBVHvb',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'ob',
        'instansi' => 'mail',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '36',
        'username' => 'afdhal19',
        'email' => 'm.afdhal.fadillah.faried@students.uin-suska.ac.id',
        'nama' => 'afdhal',
        'password_hash' => '$2y$13$MIOdcZfcddjfE3.lwP2vkuaJ8iMCIKyJhh3gLDmRJZRej4cyHm9WS',
        'password_reset_token' => null,
        'auth_key' => 'O11Kfe5UM0YpfhKA4Wx4bZGUCD74logh',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'mahasiswa',
        'instansi' => 'uin suska riau',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '37',
        'username' => 'hanafitarmizi',
        'email' => 'hanafitarmizi97@gmail.com',
        'nama' => 'hanafi tarmizi',
        'password_hash' => '$2y$13$.EMFFenh3zvAJkiaOFi0iOdT1Mu0oxoWfkFGHJCnU9Su3jOJFSNfi',
        'password_reset_token' => null,
        'auth_key' => 'iYWr_Ogw3goMEE88ja9RWPBOqWAIF11_',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'mahasiswa',
        'instansi' => 'uin suska riau',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '38',
        'username' => 'mazayarizda',
        'email' => 'mrizda63@gmail.com',
        'nama' => 'Mazaya Rizda',
        'password_hash' => '$2y$13$Y./Nyzwtla6zIIwTrbbIP.fsbztLl0soig3vOPL5DD6oKwJ97lXRG',
        'password_reset_token' => null,
        'auth_key' => 'sBoEue51vt6ua9db8uvYRXWJu4BDgE9E',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'Mahasiswa',
        'instansi' => 'Uin Suska RIau',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '39',
        'username' => 'maryantohadi',
        'email' => 'maryantohadi391@gmail.com',
        'nama' => 'hadi',
        'password_hash' => '$2y$13$0dWZMvBdoXCOapR4MAYUw.sATMKEWCcvFQbEz.573TT5lrP7QS.wK',
        'password_reset_token' => null,
        'auth_key' => '7vySwKd2hIsmyICLPmyRkExZZgbB5o_a',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'mahasiswa',
        'instansi' => 'uin suska riau',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '40',
        'username' => 'anggi_k',
        'email' => 'anggikharismaputra@gmail.com',
        'nama' => 'Anggi Kharisma Putra',
        'password_hash' => '$2y$13$KBzz1DSD/ovs3VZk.brjLeQOLMVCil3BR9MH.5NLOScRsMnyXxeXK',
        'password_reset_token' => null,
        'auth_key' => 'K84pXOJFk4sttQsOOzmGkWkkDGcFvH4s',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'Mahasiswa',
        'instansi' => 'Kampus',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '41',
        'username' => 'andrewaprianto',
        'email' => 'andrewtoaprianto@gmail.com',
        'nama' => 'Andrew Aprianto',
        'password_hash' => '$2y$13$RHYQtr1Z9052x7ECz03tpO4C.v2SH4/22GqiHoKyqGSb65tjBD9A6',
        'password_reset_token' => null,
        'auth_key' => 'pkdHX98M2dhN6KJC_ayLBUtggRQEL4SM',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'Mahasiswa',
        'instansi' => 'Gunadarma',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '42',
        'username' => 'abdulaziz2703',
        'email' => 'anzyfornia@gmail.com',
        'nama' => 'Abdul Aziz',
        'password_hash' => '$2y$13$EeFsNJQ.MQ1GSq57dz8/PeL7Col9BpAH4ZnDyBrSXXZM33ztLIvae',
        'password_reset_token' => null,
        'auth_key' => 'EyaaEkEjDNS9XJUJhn3QpJSiNQAVNgQT',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'Mahasiswa',
        'instansi' => 'UIN SUSKA RIAU',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
    [
        'id' => '43',
        'username' => 'fadilah20',
        'email' => 'fadilah.khoirudin@yahoo.com',
        'nama' => 'Fadilah Khoirudin',
        'password_hash' => '$2y$13$viK/7IJD/kFhbdD6IWzs2eMibZ6ERnYqlcuveF6FYELCtzBPn4XbW',
        'password_reset_token' => null,
        'auth_key' => '5W0ZTyIhsiSA8DFlbXK5xQvcZG9egLjH',
        'avatar' => null,
        'tempat_lahir' => null,
        'tanggal_lahir' => null,
        'alamat' => null,
        'job' => 'Student',
        'instansi' => 'Student',
        'status' => '10',
        'created_at' => '1551364390',
        'updated_at' => '1551364390',
    ],
]
        );
    }

    public function safeDown()
    {
        //$this->truncateTable('{{%user}} CASCADE');
    }
}
