# Your personal GitHub token
github_token: beaa0f2e5d87f1ade667aea651a074feba2666a6
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone
timezone: Asia/Jakarta

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: y2aa

# Virtual machine IP
ip: 192.168.8.107

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 1024
